---
title: "Bin Coordinate Data - Kmeans Clustering"
output: html_document
---

```{r setup, include=FALSE}
# LAST UPDATED: 2021/05/10
# Scott Carnie-Bronca
knitr::opts_chunk$set(echo = TRUE)

#Libraries
library(tidyverse)
library(lubridate)
library(sp)
library(leaflet)
library(gridExtra)

#Functions
source('~/Box/MPhil/Likelihood Estimation/bin_coords_kmeans.R')

#R options
options("lubridate.week.start"=1) #set first day of week to Monday instead of Sunday
```

## Load data

```{r loadData}
data = read.csv("../Data Analysis/beam_ridesCleaned.csv", row.names = 1) %>% as_tibble()
data

# dataS = as_tibble(read.csv("Data Analysis/snapshotDataAnalysis.csv", row.names = 1))
# dataS
```

Remove rows with invalid/unreasonable coordinates. Note: some rows appear to have coordinates swapped.
```{r removeInvalidCoords}
minlat = -34.98
maxlat = -34.85
minlon = 138.4
maxlon = 138.8

data = data %>%
  filter(start_lon >= minlon & start_lon <= maxlon & start_lat >= minlat & start_lat <= maxlat & +
        end_lon >= minlon & end_lon <= maxlon & end_lat >= minlat & end_lat  <= maxlat)
data
```

## Bin Data
Perform k-means clustering.
```{r binData}
k = 50 #number of clusters

start_coords = data %>% select(start_lon, start_lat) %>% as.matrix()
start_kmean = kmeans(start_coords, k)
data$start_cell = start_kmean$cluster
data %>% ggplot(aes(x = start_lon, y = start_lat, col = factor(start_cell))) + geom_point(alpha = 0.5)


end_coords = data %>% select(end_lon, end_lat) %>% as.matrix()
end_dists = spDists(end_coords, start_kmean$centers)
data$end_cell = apply(end_dists, 1, which.min)

data %>% ggplot(aes(x = end_lon, y = end_lat, col = factor(end_cell))) + geom_point(alpha = 0.5)
```



## Plot movement between cells
Plot the inter-cell movement:
```{r plotMovementBetweenCells}
data %>% 
  ggplot(aes(x = start_lon, y = start_lat, col = factor(end_cell))) + geom_point(alpha = 0.1)
data %>% 
  ggplot(aes(x = end_lon, y = end_lat, col = factor(start_cell))) + geom_point(alpha = 0.1)

data %>% 
  group_by(start_cell) %>%
  mutate(n_in_cell = n()) %>%
  ungroup() %>%
  group_by(start_cell, end_cell) %>%
  summarise(p = n()/mean(n_in_cell)) %>%
  ggplot(aes(x = start_cell, y = end_cell, fill = p)) + geom_raster()
```

<!-- ## Select a cell and generate list of hires/dropoffs -->
<!-- Generate list of events in a specific cell. -->
<!-- ```{r individualCell} -->
<!-- cellNum = 1 #cell number, from 1 to k -->

<!-- #Pickup events: -->
<!-- pickupTimes = dataCell %>% -->
<!--   group_by() %>% -->
<!--   filter(pickupCluster == cellNum) %>% -->
<!--   select(pickupTs) -->
<!-- pickupTimes = ymd_hms(pickupTimes$pickupTs) -->

<!-- dropoffTimes = dataCell %>% -->
<!--   group_by() %>% -->
<!--   filter(dropoffCluster == cellNum) %>% -->
<!--   select(dropoffTs) -->
<!-- dropoffTimes = ymd_hms(dropoffTimes$dropoffTs) -->

<!-- eventTimes = c(pickupTimes, dropoffTimes) -->
<!-- eventTypes = c(rep("H", length(pickupTimes)), rep("D", length(dropoffTimes))) -->
<!-- events = tibble(times = eventTimes, types = as.factor(eventTypes)) -->
<!-- events = events%>% -->
<!--   arrange(times) -->
<!-- events -->
<!-- ``` -->

<!-- ## Bin snapshot data -->
<!-- The snapshot data is binned using the clusters from the rides data: -->
<!-- ```{r binSnapshots} -->
<!-- dataS = as_tibble(read.csv("Data Analysis/snapshotDataAnalysis.csv", row.names = 1)) -->
<!-- coordsS = dataS %>% -->
<!--   select(geo0, geo1) %>% -->
<!--   coordinates() -->

<!-- centroids = L[[2]] -->
<!-- centroids[,1:2] = centroids[,2:1] #swap columns; should be lon then lat -->

<!-- centroidDistance = spDists(coordsS, centroids, longlat = TRUE) #in km -->

<!-- snapshotCluster = rep(0, nrow(centroidDistance)) -->
<!-- for(k in seq(1:nrow(centroidDistance))){ -->
<!--   snapshotCluster[k] = which.min(centroidDistance[k,]) -->
<!-- } -->

<!-- dataS = dataS %>% -->
<!--   mutate(cell = snapshotCluster) -->
<!-- ``` -->

<!-- ## Save binned data -->

<!-- ```{r saveData} -->
<!-- write.csv(dataCell, "Likelihood Estimation/binnedData_kmeans.csv") -->
<!-- write.csv(dataS, "Likelihood Estimation/binnedSnapshotData_kmeans.csv") -->
<!-- ``` -->
